blank_issues_enabled: false
contact_links:
  - name: Report a problem with PyPy (only report website problems here)
    url: https://foss.heptapod.net/pypy/pypy/-/issues
    about: For problems with PyPy. Use one of these links to contact us https://www.pypy.org/contact.html
