blank_issues_enabled: false
contact_links:
  - name: Report a problem with PyPy
    url: https://foss.heptapod.net/pypy/pypy/-/issues
    about: Also see <a herf="https://www.pypy.org/contact.html">Contact Us</a> to reach the PyPy team.
