blank_issues_enabled: false
contact_links:
  - name: Report a problem with PyPy
    url: https://foss.heptapod.net/pypy/pypy/-/issues
    about: Also see [contact us](https://www.pypy.org/contact.html) to reach the PyPy team.
