# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build Nikola
      uses: getnikola/nikola-action@v3
      with:
        dry_run: true
