# This is a basic workflow to help you get started with Actions

name: Nikola

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build docs
      shell: bash
      run: |
        sudo apt install virtualenv
        make build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      shell: bash
      run: |
        # reuse the venv
        venv_nikola/bin/python -m pip install ghp-import
        venv_nikola/bin/ghp-import -m"Automatic push by ghp-import" -f -p -r origin -b gh-pages public
